{
 "title": "Bess",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Bess Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT\n     strftime('%s', datetime(timestamp, 'unixepoch')) as time,\n     p, q, soc\n   FROM bess",
     "rawQueryText": "SELECT\n     strftime('%s', datetime(timestamp, 'unixepoch')) as time,\n     p, q, soc\n   FROM bess",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Bess Setpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', datetime(timestamp, 'unixepoch')) as time,\n  name,\n  value\nFROM project_data\nWHERE name = 'bess_setpoint'\n  AND timestamp IS NOT NULL\nORDER BY timestamp",
     "rawQueryText": "SELECT\n  strftime('%s', datetime(timestamp, 'unixepoch')) as time,\n  name,\n  value\nFROM project_data\nWHERE name = 'bess_setpoint'\n  AND timestamp IS NOT NULL\nORDER BY timestamp",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Watchdog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', datetime(timestamp, 'unixepoch')) as time,\n  name,\n  value\nFROM project_data\nWHERE name = 'watchdog_bess'\n  AND timestamp IS NOT NULL\nORDER BY timestamp",
     "rawQueryText": "SELECT\n  strftime('%s', datetime(timestamp, 'unixepoch')) as time,\n  name,\n  value\nFROM project_data\nWHERE name = 'watchdog_bess'\n  AND timestamp IS NOT NULL\nORDER BY timestamp",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}